/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public boolean f1()
    {
        return true;
    }
    public boolean f2()
    {
        return true;
    }
}
